### ISSUE TITLE
noise on ay-3-8910

### ISSUE THREAD

**Issue by nitrofurano** [rastersoft/fbzx#1]
I kept testing ay-3-8910 sound on fbzx, and it really sounds noisy
I tested now by experimenting opening vgm files, embedded via zxbasic-compiler - first i tried on
msx, and now on zx-spectrum
- https://dl.dropboxusercontent.com/u/795795/retrocoding/ay_sn_test/example01an_msxzxbasic_vgm.zip
- https://dl.dropboxusercontent.com/u/795795/retrocoding/ay_sn_test/vgm_ay_zxspectrum_zxbasiccompiler.zip

There i think you can confirm the noise (on the msx version, and on vgm players the sounds seems clear, and from fbzx sounds noisy - some are quite inaudible for how noisy they are ) - the zx-spectrum version i only tried on fbzx (i'm curious about how fine would they sound on a real zx-spectrum)

Thanks,
p.

**Comment by rastersoft** [comment]
Fixed in version 3.8.0. Sorry for the delay.
