### ISSUE TITLE
computer.cpp:173: possible missing break ?

### ISSUE THREAD

**Issue by dcb314** [rastersoft/fbzx#3]
case 3:     // +2A/+3
        Z80free_Out (0x1FFD, 0);
    case 1:     // 128K
    case 2:     // +2
    case 4:     // spanish 128K
        Z80free_Out (0x7FFD, 0);

Suggest either add the missing break or document the fallthrough.

**Comment by rastersoft** [comment]
Good point. In fact it is needed to ensure that the paging mode is fine in the +2A and +3.
